@BackendApi_HostAddress = http://localhost:5000

### 1. Összes könyv lekérdezése (Read - Üres lista lesz először)
GET {{BackendApi_HostAddress}}/api/books
Accept: application/json

### 2. Új könyv hozzáadása (Create)
# Kattints a "Send Request" gombra efelett a sor felett!
POST {{BackendApi_HostAddress}}/api/books
Content-Type: application/json

{
  "title": "A Gyűrűk Ura",
  "author": "J.R.R. Tolkien",
  "year": 1954
}

### 3. Egy konkrét könyv lekérdezése (Módosítsd az ID-t a létrehozás után kapottra!)
@bookId = 699c32020975b172a2b1495e
GET {{BackendApi_HostAddress}}/api/books/{{bookId}}
Accept: application/json

### 4. Könyv frissítése (Update - Módosítsd az ID-t!)
PUT {{BackendApi_HostAddress}}/api/books/{{bookId}}
Content-Type: application/json

{
  "id": "{{bookId}}",
  "title": "A Gyűrűk Ura: A Gyűrű Szövetsége",
  "author": "J.R.R. Tolkien",
  "year": 1954
}

### 5. Könyv törlése (Delete - Módosítsd az ID-t!)
DELETE {{BackendApi_HostAddress}}/api/books/{{bookId}}